/* Tabby Alchemist — content.
   This file is pure data: no DOM, no logic. Add elements and recipes here
   without touching game.js.

   Element fields:
     n     display name
     e     emoji
     f     flavor line, shown on discovery and as a grid tooltip
     base  true = available from the start
     tabby true = a real Tabby product (green border in the grid)
     final true = triggers the win screen

   Recipe format: ["inputA", "inputB", "result"] — order of inputs does not matter.
   Keep flavor on office elements dry; keep it warm and straight on real products. */

const ELEMENTS = {
  coffee:{n:"Coffee",e:"☕",base:true,f:"The real infrastructure."},
  employee:{n:"Employee",e:"🧑‍💼",base:true,f:"Badge, laptop, opinions about the coffee."},
  shopper:{n:"Shopper",e:"🛍️",base:true,f:"Cart full, thumb hovering."},
  merchant:{n:"Merchant",e:"🏪",base:true,f:"Wants the sale to actually close."},

  code:{n:"Code",e:"⌨️",f:"Compiles on the third attempt."},
  developer:{n:"Developer",e:"👩‍💻",f:"Headphones on means do not approach."},
  team:{n:"Team",e:"👥",f:"A group chat with a budget."},
  manager:{n:"Manager",e:"💼",f:"Turns meetings into more meetings."},
  office:{n:"Office",e:"🏢",f:"Where the good chairs are."},
  meeting:{n:"Meeting",e:"📆",f:"Could have been an email."},
  email:{n:"Email",e:"✉️",f:"Per my last message."},
  onboarding:{n:"Onboarding",e:"🎒",f:"Day one: eleven passwords."},
  intern:{n:"Intern",e:"🧑‍🎓",f:"Asks the question nobody else dared to."},
  deadline:{n:"Deadline",e:"⏰",f:"Immovable, until it moves."},
  standup:{n:"Standup",e:"🧍",f:"Fifteen minutes. Optimistically."},
  sprint:{n:"Sprint",e:"🏃",f:"Two weeks to do three weeks of work."},
  bug:{n:"Bug",e:"🐛",f:"Cannot reproduce on my machine."},
  hotfix:{n:"Hotfix",e:"🩹",f:"Straight to prod. Fingers crossed."},
  codeReview:{n:"Code Review",e:"🔍",f:"Looks good to me. (Did not read it.)"},
  mergeConflict:{n:"Merge Conflict",e:"💥",f:"Two people were right."},
  jira:{n:"Jira Ticket",e:"🎫",f:"Filed. Groomed. Forgotten. Reopened."},
  slack:{n:"Slack Message",e:"💬",f:"“Quick question” — 40 minutes ago."},
  friday:{n:"Friday",e:"🍺",f:"Two weeks done. Monday is Monday's problem."},
  monday:{n:"Monday",e:"😵‍💫",f:"The weekend was a rumour."},
  okr:{n:"OKR",e:"📌",f:"Seventy percent is a win, apparently."},
  kpi:{n:"KPI",e:"📈",f:"A number everyone now optimises for."},
  roadmap:{n:"Roadmap",e:"🗺️",f:"Accurate for about a week."},
  retro:{n:"Retro",e:"🔄",f:"What went well: we had the retro."},
  achiever:{n:"Achiever",e:"🏅",f:"Hit the number. Asked for the next one."},
  oneOnOne:{n:"1:1",e:"🗣️",f:"“So — how are things?”"},
  performanceReview:{n:"Performance Review",e:"📋",f:"Six months compressed into one form."},
  promotion:{n:"Promotion",e:"🎖️",f:"New title, same laptop."},
  burnout:{n:"Burnout",e:"🥵",f:"The sprint that never ended."},
  vacation:{n:"Vacation",e:"🏝️",f:"Out of office. Reading email anyway."},
  allHands:{n:"All-Hands",e:"📢",f:"Nine hundred people, one unmuted microphone."},
  buzzword:{n:"Buzzword",e:"🗯️",f:"Directionally impactful, going forward."},
  synergy:{n:"Synergy",e:"🔗",f:"Nobody has ever seen one in the wild."},
  pivot:{n:"Pivot",e:"↩️",f:"The roadmap was more of a suggestion."},
  brainstorm:{n:"Brainstorm",e:"💡",f:"Forty sticky notes. One survives."},
  idea:{n:"Idea",e:"🧠",f:"Obvious in hindsight."},
  mvp:{n:"MVP",e:"🧪",f:"Minimum, viable, and shipped anyway."},
  launch:{n:"Launch",e:"🚀",f:"Green light. Hold your breath."},

  // ---- Tabby products (real) ----
  checkout:{n:"Checkout",e:"🧾",f:"The last screen between cart and yes."},
  split4:{n:"Split in 4",e:"4️⃣",tabby:true,f:"One order, four payments, no interest."},
  payLater:{n:"Pay Later",e:"⏳",tabby:true,f:"Buy now, settle up later."},
  instantApproval:{n:"Instant Approval",e:"✅",tabby:true,f:"Seconds to decide, so checkout never stalls."},
  interestFree:{n:"Interest-Free",e:"✨",tabby:true,f:"The price you see is the price you pay."},
  tabbyShop:{n:"Tabby Shop",e:"🛒",tabby:true,f:"Somewhere to discover what to buy next."},
  tabbyCard:{n:"Tabby Card",e:"💠",tabby:true,f:"Tabby, everywhere cards are accepted."},
  tabbyPlus:{n:"Tabby Plus",e:"⭐",tabby:true,f:"Rewards for the shoppers who keep coming back."},
  tabbyCare:{n:"Tabby Care",e:"🧯",tabby:true,f:"Support that picks up when something goes wrong."},
  tabbyApp:{n:"Tabby App",e:"📲",tabby:true,f:"The whole thing, in your pocket."},
  superApp:{n:"Super App",e:"📱",tabby:true,f:"Shopping, payments and rewards under one roof."},

  // ===== Expanded content (v2): office, devops, data, design, growth, sales, HR, fintech ops, markets =====
  laptop:{n:"Laptop",e:"💻",f:"Company property. Stickers: personal."},
  badge:{n:"Badge",e:"🪪",f:"Tap to enter. Forgotten twice."},
  wfh:{n:"WFH",e:"🏠",f:"Pants optional, camera off."},
  zoomCall:{n:"Zoom Call",e:"🎥",f:"You're on mute."},
  headphones:{n:"Headphones",e:"🎧",f:"On means do not approach."},
  vpn:{n:"VPN",e:"🔐",f:"Connected. Reconnecting. Connected."},
  slackHuddle:{n:"Slack Huddle",e:"🔊",f:"Audio only. Someone's chewing."},
  emojiReact:{n:"Emoji React",e:"👍",f:"Shipped the thumbs-up."},
  gif:{n:"Reply-All GIF",e:"🕺",f:"Reply-all, but make it dance."},
  calendarTetris:{n:"Calendar Tetris",e:"🗓️",f:"No free slot until Q3."},
  deploy:{n:"Deploy",e:"📦",f:"Ship it. Watch the graphs."},
  ci:{n:"CI",e:"🔁",f:"Green check or it didn't happen."},
  rollback:{n:"Rollback",e:"⏪",f:"Undo, quickly, quietly."},
  featureFlag:{n:"Feature Flag",e:"🚩",f:"On for two percent of users."},
  incident:{n:"Incident",e:"🚨",f:"Sev-1. Everyone's awake now."},
  pager:{n:"Pager",e:"📟",f:"3 a.m. and it's your week."},
  onCall:{n:"On-Call",e:"🔕",f:"One week of jumpiness."},
  postmortem:{n:"Postmortem",e:"🪦",f:"Blameless. Mostly."},
  rootCause:{n:"Root Cause",e:"🧐",f:"It was DNS. It's always DNS."},
  uptime:{n:"Uptime",e:"🟢",f:"Ninety-nine point nine, they promised."},
  outage:{n:"Outage",e:"🔴",f:"Status page goes red."},
  techDebt:{n:"Tech Debt",e:"🕳️",f:"Interest compounds."},
  refactor:{n:"Refactor",e:"🧹",f:"Two weeks, no new features."},
  legacy:{n:"Legacy Code",e:"🏚️",f:"Nobody knows how it works."},
  data:{n:"Data",e:"🗃️",f:"Rows nobody cleaned."},
  dashboard:{n:"Dashboard",e:"📊",f:"Green if you squint."},
  sql:{n:"SQL",e:"🧮",f:"SELECT * FROM regret."},
  etl:{n:"ETL",e:"🛠️",f:"Extract, transform, lose a row."},
  model:{n:"ML Model",e:"🦾",f:"Confident and occasionally right."},
  abTest:{n:"A/B Test",e:"🅰️",f:"B won. Nobody knows why."},
  metric:{n:"Metric",e:"📶",f:"Up and to the right, ideally."},
  insight:{n:"Insight",e:"🔮",f:"Obvious after the chart."},
  designer:{n:"Designer",e:"🎨",f:"Pixels have feelings."},
  wireframe:{n:"Wireframe",e:"✏️",f:"Boxes and arrows."},
  figma:{n:"Figma",e:"🖌️",f:"Where the arrows live."},
  prototype:{n:"Prototype",e:"🧷",f:"Clickable, barely."},
  userResearch:{n:"User Research",e:"🕵️",f:"Watching people struggle."},
  persona:{n:"Persona",e:"🪞",f:"A made-up user named Sarah."},
  usability:{n:"Usability",e:"👆",f:"Where do I tap?"},
  designSystem:{n:"Design System",e:"🧩",f:"One button, one truth."},
  accessibility:{n:"Accessibility",e:"♿",f:"Works for everyone or it doesn't."},
  marketer:{n:"Marketer",e:"📣",f:"Owns the funnel, blames the product."},
  campaign:{n:"Campaign",e:"🎯",f:"Q4 push, all channels."},
  funnel:{n:"Funnel",e:"🫗",f:"Wide top, sad bottom."},
  conversionRate:{n:"Conversion Rate",e:"💹",f:"Two percent, celebrated."},
  landingPage:{n:"Landing Page",e:"🖥️",f:"One button, big promise."},
  seo:{n:"SEO",e:"🔠",f:"Ranking for 'pay later'."},
  adSpend:{n:"Ad Spend",e:"🪧",f:"CAC creeping up."},
  viral:{n:"Viral",e:"🦠",f:"Unplanned, unstoppable."},
  influencer:{n:"Influencer",e:"🤳",f:"Paid in product."},
  salesRep:{n:"Sales Rep",e:"🤝",f:"Always be closing."},
  lead:{n:"Lead",e:"🎣",f:"Maybe a customer."},
  demo:{n:"Demo",e:"🎬",f:"Works on the second try."},
  salesPipeline:{n:"Sales Pipeline",e:"🧲",f:"Half of it is stale."},
  quota:{n:"Quota",e:"🥅",f:"This quarter's impossible number."},
  dealDesk:{n:"Deal Desk",e:"📝",f:"Discount approved, reluctantly."},
  merchantDeal:{n:"Merchant Deal",e:"🏷️",f:"Signed. Onboarding next."},
  integration:{n:"Integration",e:"🔌",f:"Two weeks, they said."},
  goLive:{n:"Go-Live",e:"🟩",f:"Merchant is live on Tabby."},
  hr:{n:"HR",e:"🧑‍⚖️",f:"Owns the awkward conversations."},
  recruiter:{n:"Recruiter",e:"🕵️‍♀️",f:"Ghosts more than a dating app."},
  candidate:{n:"Candidate",e:"🙋",f:"Looks great on paper."},
  offer:{n:"Offer",e:"📨",f:"Exploding in 48 hours."},
  counterOffer:{n:"Counter-Offer",e:"🃏",f:"Suddenly you're valued."},
  resignation:{n:"Resignation",e:"📄",f:"Two weeks' notice, one relieved sigh."},
  attrition:{n:"Attrition",e:"🚪",f:"Backfill approved in Q3."},
  exitInterview:{n:"Exit Interview",e:"👋",f:"Honest, finally."},
  alumni:{n:"Alumni",e:"🎓",f:"Still in the Slack, somehow."},
  reorg:{n:"Reorg",e:"🔀",f:"Same people, new boxes."},
  layoff:{n:"Layoff",e:"📉",f:"It's not you, it's the runway."},
  severance:{n:"Severance",e:"🧧",f:"Two weeks and a thank-you."},
  pto:{n:"PTO",e:"🌴",f:"Approved, pending 'a good time'."},
  equity:{n:"Equity",e:"📜",f:"Vests in four years. Probably."},
  bonus:{n:"Bonus",e:"🎁",f:"Discretionary, they remind you."},
  raise:{n:"Raise",e:"💵",f:"Beat inflation. Barely."},
  downPayment:{n:"Down Payment",e:"💳",f:"Twenty-five percent, today."},
  instalment:{n:"Instalment",e:"📅",f:"One of four, on time."},
  noLateFees:{n:"No Late Fees",e:"🕊️",f:"Miss a date, no penalty spiral."},
  creditLimit:{n:"Credit Limit",e:"📏",f:"How much Tabby trusts you."},
  underwriting:{n:"Underwriting",e:"🔬",f:"Approve in a blink, safely."},
  chargeback:{n:"Chargeback",e:"🔙",f:"Money, reversed."},
  refund:{n:"Refund",e:"🪙",f:"Back to the card in days."},
  dispute:{n:"Dispute",e:"⚖️",f:"Both sides submit screenshots."},
  fraud:{n:"Fraud",e:"🥷",f:"A pattern that shouldn't exist."},
  fraudModel:{n:"Fraud Model",e:"🛡️",f:"Learns the tricks faster than they change."},
  riskEngine:{n:"Risk Engine",e:"⚙️",f:"Scores every order in real time."},
  compliance:{n:"Compliance",e:"🏛️",f:"The rules about the rules."},
  aml:{n:"AML",e:"🧿",f:"Know your customer, truly."},
  regulator:{n:"Regulator",e:"👮",f:"Politely, a lot of questions."},
  licence:{n:"Licence",e:"📃",f:"Permission to operate."},
  wallet:{n:"Wallet",e:"👛",f:"Money, stored and sent."},
  topUp:{n:"Top-Up",e:"🔋",f:"Add funds, spend later."},
  payout:{n:"Payout",e:"🏦",f:"Merchant gets paid on time."},
  settlement:{n:"Settlement",e:"📒",f:"Everyone's numbers agree."},
  ledger:{n:"Ledger",e:"📗",f:"Single source of truth."},
  reconciliation:{n:"Reconciliation",e:"📕",f:"Numbers matched by month-end."},
  riyadh:{n:"Riyadh",e:"🕌",f:"Where it all scales."},
  dubai:{n:"Dubai",e:"🏙️",f:"Skyline of early adopters."},
  ksa:{n:"Saudi Arabia",e:"🇸🇦",f:"The biggest market."},
  uae:{n:"UAE",e:"🇦🇪",f:"Second home."},
  mena:{n:"MENA",e:"🌍",f:"The whole region, one wallet."},
  ramadanSale:{n:"Ramadan Sale",e:"🌙",f:"Peak shopping season."},
  whiteFriday:{n:"White Friday",e:"🔖",f:"The region's Black Friday."},
  arabic:{n:"Arabic RTL",e:"🗨️",f:"Right-to-left, done right."},
  freeLunch:{n:"Free Lunch",e:"🍕",f:"Catered. Gone in ten minutes."},
  pingPong:{n:"Ping-Pong",e:"🏓",f:"Table's always taken."},
  swag:{n:"Swag",e:"🧢",f:"Another hoodie for the pile."},
  allNighter:{n:"All-Nighter",e:"🌃",f:"Ship at dawn."},
  crunch:{n:"Crunch",e:"😩",f:"Two sprints, no gap."},
  scopeCreep:{n:"Scope Creep",e:"🐙",f:"Just one more small thing."},
  dependency:{n:"Dependency",e:"⛓️",f:"Blocked by another team."},
  blocker:{n:"Blocker",e:"🚧",f:"Cannot proceed."},
  escalation:{n:"Escalation",e:"☎️",f:"Loop in the VP."},
  warRoom:{n:"War Room",e:"🚒",f:"Everyone in one channel."},
  northStar:{n:"North-Star Metric",e:"🌟",f:"The one number that matters."},
  productLed:{n:"Product-Led",e:"🧭",f:"The product sells itself. Ideally."},
  retention:{n:"Retention",e:"💚",f:"They come back next month."},
  rewards:{n:"Rewards",e:"🏵️",f:"Points that feel like winning."},
  loyalty:{n:"Loyalty",e:"💛",f:"Not a habit — a preference."},
  nps:{n:"NPS",e:"😊",f:"Would you recommend us? (1–10)"},
  security:{n:"Security",e:"🔒",f:"Least privilege, most tickets."},
  apiKey:{n:"API Key",e:"🗝️",f:"Do not commit this."},
  twoFA:{n:"2FA",e:"🔢",f:"Enter the code we just sent."},
  encryption:{n:"Encryption",e:"🧬",f:"Unreadable, on purpose."},
  audit:{n:"Audit",e:"📎",f:"Everything, on the record."},
  soc2:{n:"SOC 2",e:"📁",f:"The badge on the website."},
  backup:{n:"Backup",e:"💾",f:"Restored, once, successfully."},
  server:{n:"Server",e:"🗄️",f:"Hums in a room somewhere."},
  cloud:{n:"Cloud",e:"☁️",f:"Someone else's computer."},
  scaling:{n:"Scaling",e:"🪜",f:"More users, more servers."},
  latency:{n:"Latency",e:"🐌",f:"The spinner of doom."},
  cache:{n:"Cache",e:"🧊",f:"Fast, until it's stale."},
  microservice:{n:"Microservice",e:"🔲",f:"One of two hundred."},
  monolith:{n:"Monolith",e:"🗿",f:"One repo to rule them all."},
  kubernetes:{n:"Kubernetes",e:"☸️",f:"YAML all the way down."},
  techLead:{n:"Tech Lead",e:"🧑‍🏫",f:"Codes less, unblocks more."},
  architect:{n:"Architect",e:"📐",f:"Draws the boxes."},
  coffeeMachine:{n:"Coffee Machine",e:"🫖",f:"Broken by 10 a.m."},
  freeSnacks:{n:"Free Snacks",e:"🍫",f:"The real retention strategy."},
  oooReply:{n:"OOO Reply",e:"🤖",f:"Auto-reply: back next week."},
  replyAll:{n:"Reply-All",e:"📩",f:"The thread that would not die."},

  productOfYear:{n:"Product of the Year",e:"🏆",final:true,f:"Endless standups, somehow, into something people love."},
};

const RAW = [
  // ---- People & dev ----
  ["employee","coffee","code"],
  ["employee","code","developer"],
  ["employee","employee","team"],
  ["employee","team","manager"],
  ["team","merchant","office"],
  ["manager","team","meeting"],
  ["office","employee","email"],
  ["manager","email","onboarding"],
  ["onboarding","coffee","intern"],
  ["meeting","code","deadline"],
  ["meeting","team","standup"],
  ["standup","deadline","sprint"],
  ["code","deadline","bug"],
  ["bug","deadline","hotfix"],
  ["code","developer","codeReview"],
  ["code","code","mergeConflict"],
  ["bug","manager","jira"],
  ["meeting","email","slack"],
  ["sprint","deadline","friday"],
  ["bug","friday","monday"],
  ["manager","meeting","okr"],
  ["okr","team","kpi"],
  ["okr","sprint","roadmap"],
  ["sprint","monday","retro"],
  ["employee","kpi","achiever"],
  ["manager","employee","oneOnOne"],
  ["oneOnOne","kpi","performanceReview"],
  ["performanceReview","achiever","promotion"],
  ["deadline","hotfix","burnout"],
  ["burnout","employee","vacation"],
  ["office","meeting","allHands"],
  ["meeting","roadmap","buzzword"],
  ["buzzword","team","synergy"],
  ["roadmap","deadline","pivot"],
  ["meeting","coffee","brainstorm"],
  ["brainstorm","developer","idea"],
  ["idea","sprint","mvp"],
  ["mvp","team","launch"],

  // ---- Tabby products ----
  ["shopper","merchant","checkout"],
  ["checkout","shopper","split4"],
  ["split4","merchant","payLater"],
  ["payLater","code","instantApproval"],
  ["payLater","shopper","interestFree"],
  ["interestFree","merchant","tabbyShop"],
  ["payLater","interestFree","tabbyCard"],
  ["tabbyCard","shopper","tabbyPlus"],
  ["shopper","hotfix","tabbyCare"],
  ["tabbyCard","code","tabbyApp"],
  ["tabbyApp","tabbyShop","superApp"],

  // ===== Expanded recipes (v2) =====
  ["developer","office","laptop"],
  ["onboarding","employee","badge"],
  ["employee","laptop","wfh"],
  ["meeting","wfh","zoomCall"],
  ["developer","coffee","headphones"],
  ["laptop","office","vpn"],
  ["slack","standup","slackHuddle"],
  ["slack","idea","emojiReact"],
  ["slack","friday","gif"],
  ["meeting","deadline","calendarTetris"],
  ["code","launch","deploy"],
  ["code","deploy","ci"],
  ["deploy","incident","rollback"],
  ["deploy","idea","featureFlag"],
  ["bug","deploy","incident"],
  ["incident","deadline","pager"],
  ["pager","team","onCall"],
  ["incident","retro","postmortem"],
  ["postmortem","data","rootCause"],
  ["deploy","kpi","uptime"],
  ["incident","uptime","outage"],
  ["hotfix","codeReview","techDebt"],
  ["techDebt","developer","refactor"],
  ["techDebt","deadline","legacy"],
  ["code","kpi","data"],
  ["data","okr","dashboard"],
  ["data","developer","sql"],
  ["data","deploy","etl"],
  ["data","idea","model"],
  ["featureFlag","data","abTest"],
  ["dashboard","okr","metric"],
  ["data","brainstorm","insight"],
  ["employee","idea","designer"],
  ["designer","brainstorm","wireframe"],
  ["designer","laptop","figma"],
  ["wireframe","figma","prototype"],
  ["designer","shopper","userResearch"],
  ["userResearch","idea","persona"],
  ["prototype","userResearch","usability"],
  ["figma","codeReview","designSystem"],
  ["designSystem","userResearch","accessibility"],
  ["team","kpi","marketer"],
  ["marketer","idea","campaign"],
  ["campaign","data","funnel"],
  ["funnel","checkout","conversionRate"],
  ["campaign","designer","landingPage"],
  ["landingPage","data","seo"],
  ["campaign","manager","adSpend"],
  ["campaign","launch","viral"],
  ["campaign","shopper","influencer"],
  ["employee","merchant","salesRep"],
  ["salesRep","shopper","lead"],
  ["salesRep","prototype","demo"],
  ["lead","lead","salesPipeline"],
  ["salesRep","kpi","quota"],
  ["quota","manager","dealDesk"],
  ["salesRep","merchant","merchantDeal"],
  ["merchantDeal","developer","integration"],
  ["integration","launch","goLive"],
  ["office","manager","hr"],
  ["hr","email","recruiter"],
  ["recruiter","intern","candidate"],
  ["candidate","manager","offer"],
  ["offer","manager","counterOffer"],
  ["burnout","offer","resignation"],
  ["resignation","team","attrition"],
  ["resignation","hr","exitInterview"],
  ["exitInterview","coffee","alumni"],
  ["manager","manager","reorg"],
  ["reorg","deadline","layoff"],
  ["layoff","hr","severance"],
  ["vacation","manager","pto"],
  ["achiever","promotion","equity"],
  ["kpi","achiever","bonus"],
  ["promotion","manager","raise"],
  ["split4","shopper","downPayment"],
  ["payLater","deadline","instalment"],
  ["interestFree","deadline","noLateFees"],
  ["instantApproval","shopper","creditLimit"],
  ["instantApproval","data","underwriting"],
  ["tabbyCare","bug","chargeback"],
  ["tabbyCare","checkout","refund"],
  ["chargeback","shopper","dispute"],
  ["data","bug","fraud"],
  ["fraud","model","fraudModel"],
  ["fraudModel","underwriting","riskEngine"],
  ["riskEngine","office","compliance"],
  ["compliance","data","aml"],
  ["compliance","allHands","regulator"],
  ["regulator","compliance","licence"],
  ["tabbyCard","licence","wallet"],
  ["wallet","shopper","topUp"],
  ["wallet","merchant","payout"],
  ["payout","kpi","settlement"],
  ["settlement","code","ledger"],
  ["ledger","deadline","reconciliation"],
  ["goLive","merchant","riyadh"],
  ["goLive","shopper","dubai"],
  ["riyadh","kpi","ksa"],
  ["dubai","kpi","uae"],
  ["ksa","uae","mena"],
  ["mena","campaign","ramadanSale"],
  ["campaign","friday","whiteFriday"],
  ["tabbyApp","mena","arabic"],
  ["office","friday","freeLunch"],
  ["friday","team","pingPong"],
  ["marketer","team","swag"],
  ["deadline","coffee","allNighter"],
  ["sprint","sprint","crunch"],
  ["roadmap","idea","scopeCreep"],
  ["jira","roadmap","dependency"],
  ["dependency","deadline","blocker"],
  ["blocker","manager","escalation"],
  ["escalation","team","warRoom"],
  ["okr","roadmap","northStar"],
  ["northStar","mvp","productLed"],
  ["tabbyPlus","kpi","retention"],
  ["tabbyPlus","checkout","rewards"],
  ["rewards","retention","loyalty"],
  ["retention","userResearch","nps"],
  ["compliance","code","security"],
  ["integration","security","apiKey"],
  ["security","shopper","twoFA"],
  ["security","data","encryption"],
  ["compliance","retro","audit"],
  ["audit","compliance","soc2"],
  ["data","deadline","backup"],
  ["code","office","server"],
  ["server","deploy","cloud"],
  ["cloud","kpi","scaling"],
  ["server","shopper","latency"],
  ["latency","data","cache"],
  ["code","cloud","microservice"],
  ["code","legacy","monolith"],
  ["microservice","cloud","kubernetes"],
  ["developer","promotion","techLead"],
  ["techLead","roadmap","architect"],
  ["office","coffee","coffeeMachine"],
  ["coffeeMachine","team","freeSnacks"],
  ["vacation","email","oooReply"],
  ["email","allHands","replyAll"],

  // ---- Finale ----
  ["launch","superApp","productOfYear"],
];
