/* Tabby Alchemist — content.
   This file is pure data: no DOM, no logic. Add elements and recipes here
   without touching game.js.

   Element fields:
     n     display name
     e     emoji
     f     flavor line, shown on discovery and as a grid tooltip
     base  true = available from the start
     tabby true = a real Tabby product (green border in the grid)
     final true = triggers the win screen

   Recipe format: ["inputA", "inputB", "result"] — order of inputs does not matter.
   Keep flavor on office elements dry; keep it warm and straight on real products. */

const ELEMENTS = {
  coffee:{n:"Coffee",e:"☕",base:true,f:"The real infrastructure."},
  employee:{n:"Employee",e:"🧑‍💼",base:true,f:"Badge, laptop, opinions about the coffee."},
  shopper:{n:"Shopper",e:"🛍️",base:true,f:"Cart full, thumb hovering."},
  merchant:{n:"Merchant",e:"🏪",base:true,f:"Wants the sale to actually close."},

  code:{n:"Code",e:"⌨️",f:"Compiles on the third attempt."},
  developer:{n:"Developer",e:"👩‍💻",f:"Headphones on means do not approach."},
  team:{n:"Team",e:"👥",f:"A group chat with a budget."},
  manager:{n:"Manager",e:"💼",f:"Turns meetings into more meetings."},
  office:{n:"Office",e:"🏢",f:"Where the good chairs are."},
  meeting:{n:"Meeting",e:"📆",f:"Could have been an email."},
  email:{n:"Email",e:"✉️",f:"Per my last message."},
  onboarding:{n:"Onboarding",e:"🎒",f:"Day one: eleven passwords."},
  intern:{n:"Intern",e:"🧑‍🎓",f:"Asks the question nobody else dared to."},
  deadline:{n:"Deadline",e:"⏰",f:"Immovable, until it moves."},
  standup:{n:"Standup",e:"🧍",f:"Fifteen minutes. Optimistically."},
  sprint:{n:"Sprint",e:"🏃",f:"Two weeks to do three weeks of work."},
  bug:{n:"Bug",e:"🐛",f:"Cannot reproduce on my machine."},
  hotfix:{n:"Hotfix",e:"🩹",f:"Straight to prod. Fingers crossed."},
  codeReview:{n:"Code Review",e:"🔍",f:"Looks good to me. (Did not read it.)"},
  mergeConflict:{n:"Merge Conflict",e:"💥",f:"Two people were right."},
  jira:{n:"Jira Ticket",e:"🎫",f:"Filed. Groomed. Forgotten. Reopened."},
  slack:{n:"Slack Message",e:"💬",f:"“Quick question” — 40 minutes ago."},
  friday:{n:"Friday",e:"🍺",f:"Two weeks done. Monday is Monday's problem."},
  monday:{n:"Monday",e:"😵‍💫",f:"The weekend was a rumour."},
  okr:{n:"OKR",e:"📌",f:"Seventy percent is a win, apparently."},
  kpi:{n:"KPI",e:"📈",f:"A number everyone now optimises for."},
  roadmap:{n:"Roadmap",e:"🗺️",f:"Accurate for about a week."},
  retro:{n:"Retro",e:"🔄",f:"What went well: we had the retro."},
  achiever:{n:"Achiever",e:"🏅",f:"Hit the number. Asked for the next one."},
  oneOnOne:{n:"1:1",e:"🗣️",f:"“So — how are things?”"},
  performanceReview:{n:"Performance Review",e:"📋",f:"Six months compressed into one form."},
  promotion:{n:"Promotion",e:"🎖️",f:"New title, same laptop."},
  burnout:{n:"Burnout",e:"🥵",f:"The sprint that never ended."},
  vacation:{n:"Vacation",e:"🏝️",f:"Out of office. Reading email anyway."},
  allHands:{n:"All-Hands",e:"📢",f:"Nine hundred people, one unmuted microphone."},
  buzzword:{n:"Buzzword",e:"🗯️",f:"Directionally impactful, going forward."},
  synergy:{n:"Synergy",e:"🔗",f:"Nobody has ever seen one in the wild."},
  pivot:{n:"Pivot",e:"↩️",f:"The roadmap was more of a suggestion."},
  brainstorm:{n:"Brainstorm",e:"💡",f:"Forty sticky notes. One survives."},
  idea:{n:"Idea",e:"🧠",f:"Obvious in hindsight."},
  mvp:{n:"MVP",e:"🧪",f:"Minimum, viable, and shipped anyway."},
  launch:{n:"Launch",e:"🚀",f:"Green light. Hold your breath."},

  // ---- Tabby products (real) ----
  checkout:{n:"Checkout",e:"🧾",f:"The last screen between cart and yes."},
  split4:{n:"Split in 4",e:"4️⃣",tabby:true,f:"One order, four payments, no interest."},
  payLater:{n:"Pay Later",e:"⏳",tabby:true,f:"Buy now, settle up later."},
  instantApproval:{n:"Instant Approval",e:"✅",tabby:true,f:"Seconds to decide, so checkout never stalls."},
  interestFree:{n:"Interest-Free",e:"✨",tabby:true,f:"The price you see is the price you pay."},
  tabbyShop:{n:"Tabby Shop",e:"🛒",tabby:true,f:"Somewhere to discover what to buy next."},
  tabbyCard:{n:"Tabby Card",e:"💠",tabby:true,f:"Tabby, everywhere cards are accepted."},
  tabbyPlus:{n:"Tabby Plus",e:"⭐",tabby:true,f:"Rewards for the shoppers who keep coming back."},
  tabbyCare:{n:"Tabby Care",e:"🧯",tabby:true,f:"Support that picks up when something goes wrong."},
  tabbyApp:{n:"Tabby App",e:"📲",tabby:true,f:"The whole thing, in your pocket."},
  superApp:{n:"Super App",e:"📱",tabby:true,f:"Shopping, payments and rewards under one roof."},

  // ===== Expanded content (curated): devops, data, sales, HR, risk, wallet, compliance =====
  deploy:{n:"Deploy",e:"📦",f:"Ship it. Watch the graphs."},
  ci:{n:"CI",e:"🔁",f:"Green check or it didn't happen."},
  incident:{n:"Incident",e:"🚨",f:"A bug that made it to prod."},
  rollback:{n:"Rollback",e:"⏪",f:"Undo the deploy, quietly."},
  postmortem:{n:"Postmortem",e:"🪦",f:"A retro for the incident. Blameless, mostly."},
  techDebt:{n:"Tech Debt",e:"🕳️",f:"Hotfix on hotfix. Interest compounds."},
  refactor:{n:"Refactor",e:"🧹",f:"A sprint spent paying it down."},
  data:{n:"Data",e:"🗃️",f:"Every checkout, logged."},
  dashboard:{n:"Dashboard",e:"📊",f:"The KPIs, finally visible."},
  model:{n:"ML Model",e:"🦾",f:"A developer trained it on the data."},
  salesRep:{n:"Sales Rep",e:"🤝",f:"Signs merchants for a living."},
  lead:{n:"Lead",e:"🎣",f:"A shopper the rep is chasing."},
  demo:{n:"Demo",e:"🎬",f:"The rep shows the MVP."},
  merchantDeal:{n:"Merchant Deal",e:"🏷️",f:"Signed. Onboarding next."},
  integration:{n:"Integration",e:"🔌",f:"Devs wire the merchant in."},
  goLive:{n:"Go-Live",e:"🟩",f:"The merchant is live on Tabby."},
  merchantNetwork:{n:"Merchant Network",e:"🕸️",f:"Enough deals to matter."},
  conversion:{n:"Conversion",e:"💹",f:"Interest-free lifts the yes."},
  gmv:{n:"GMV",e:"💵",f:"Volume across every store."},
  hr:{n:"HR",e:"🧑‍⚖️",f:"Owns onboarding and the awkward talks."},
  recruiter:{n:"Recruiter",e:"🕵️‍♀️",f:"HR, reaching out."},
  candidate:{n:"Candidate",e:"🙋",f:"A promising intern, courted."},
  offer:{n:"Offer",e:"📨",f:"The manager makes it. 48 hours to decide."},
  resignation:{n:"Resignation",e:"📄",f:"Burnt out, and a better offer."},
  bonus:{n:"Bonus",e:"🎁",f:"Hit the numbers, get a little extra."},
  raise:{n:"Raise",e:"💰",f:"A good review, in money."},
  fraud:{n:"Fraud",e:"🥷",f:"A pattern in the data that shouldn't exist."},
  riskEngine:{n:"Risk Engine",e:"⚙️",f:"Code that scores the fraud away."},
  underwriting:{n:"Underwriting",e:"🔬",f:"Sizing up a shopper, safely."},
  creditLimit:{n:"Credit Limit",e:"📏",f:"How much Tabby trusts you."},
  downPayment:{n:"Down Payment",e:"💳",f:"The first of four, at checkout."},
  instalment:{n:"Instalment",e:"📅",f:"One payment of the four."},
  noLateFees:{n:"No Late Fees",e:"🕊️",f:"Miss a date, no penalty spiral."},
  refund:{n:"Refund",e:"🪙",f:"Care sends it back to the card."},
  chargeback:{n:"Chargeback",e:"🔙",f:"Something broke; money reversed."},
  dispute:{n:"Dispute",e:"⚖️",f:"Both sides submit screenshots."},
  wallet:{n:"Wallet",e:"👛",f:"The card, living in the app."},
  topUp:{n:"Top-Up",e:"🔋",f:"Add funds, spend later."},
  payout:{n:"Payout",e:"🏦",f:"The merchant gets paid."},
  ledger:{n:"Ledger",e:"📗",f:"Every payout, reconciled."},
  rewards:{n:"Rewards",e:"🏵️",f:"Plus points, earned at checkout."},
  loyalty:{n:"Loyalty",e:"💛",f:"Rewards turn shoppers into regulars."},
  compliance:{n:"Compliance",e:"🏛️",f:"The rules the risk engine enforces."},
  audit:{n:"Audit",e:"📎",f:"Compliance, reviewed end to end."},
  security:{n:"Security",e:"🔒",f:"Least privilege, most tickets."},
  licence:{n:"Licence",e:"📃",f:"Permission to operate."},
  allNighter:{n:"All-Nighter",e:"🌃",f:"Coffee versus the deadline."},
  freeLunch:{n:"Free Lunch",e:"🍕",f:"Catered Friday. Gone in ten minutes."},
  blocker:{n:"Blocker",e:"🚧",f:"A bug stops the sprint."},
  escalation:{n:"Escalation",e:"☎️",f:"Blocked long enough — loop in the VP."},
  northStar:{n:"North-Star Metric",e:"🌟",f:"The one number that matters."},

  productOfYear:{n:"Product of the Year",e:"🏆",final:true,f:"Endless standups, somehow, into something people love."},
};

const RAW = [
  // ---- People & dev ----
  ["employee","coffee","code"],
  ["employee","code","developer"],
  ["employee","employee","team"],
  ["employee","team","manager"],
  ["team","merchant","office"],
  ["manager","team","meeting"],
  ["office","employee","email"],
  ["manager","email","onboarding"],
  ["onboarding","coffee","intern"],
  ["meeting","code","deadline"],
  ["meeting","team","standup"],
  ["standup","deadline","sprint"],
  ["code","deadline","bug"],
  ["bug","deadline","hotfix"],
  ["code","developer","codeReview"],
  ["code","code","mergeConflict"],
  ["bug","manager","jira"],
  ["meeting","email","slack"],
  ["sprint","deadline","friday"],
  ["bug","friday","monday"],
  ["manager","meeting","okr"],
  ["okr","team","kpi"],
  ["okr","sprint","roadmap"],
  ["sprint","monday","retro"],
  ["employee","kpi","achiever"],
  ["manager","employee","oneOnOne"],
  ["oneOnOne","kpi","performanceReview"],
  ["performanceReview","achiever","promotion"],
  ["deadline","hotfix","burnout"],
  ["burnout","employee","vacation"],
  ["office","meeting","allHands"],
  ["meeting","roadmap","buzzword"],
  ["buzzword","team","synergy"],
  ["roadmap","deadline","pivot"],
  ["meeting","coffee","brainstorm"],
  ["brainstorm","developer","idea"],
  ["idea","sprint","mvp"],
  ["mvp","team","launch"],

  // ---- Tabby products ----
  ["shopper","merchant","checkout"],
  ["checkout","shopper","split4"],
  ["split4","merchant","payLater"],
  ["payLater","code","instantApproval"],
  ["payLater","shopper","interestFree"],
  ["interestFree","merchant","tabbyShop"],
  ["payLater","interestFree","tabbyCard"],
  ["tabbyCard","shopper","tabbyPlus"],
  ["shopper","hotfix","tabbyCare"],
  ["tabbyCard","code","tabbyApp"],
  ["tabbyApp","tabbyShop","superApp"],

  // ===== Expanded recipes (curated) =====
  ["code","launch","deploy"],
  ["code","deploy","ci"],
  ["bug","deploy","incident"],
  ["incident","deploy","rollback"],
  ["incident","retro","postmortem"],
  ["hotfix","hotfix","techDebt"],
  ["techDebt","sprint","refactor"],
  ["checkout","code","data"],
  ["data","kpi","dashboard"],
  ["data","developer","model"],
  ["employee","merchant","salesRep"],
  ["salesRep","shopper","lead"],
  ["salesRep","mvp","demo"],
  ["salesRep","merchant","merchantDeal"],
  ["merchantDeal","developer","integration"],
  ["integration","launch","goLive"],
  ["merchantDeal","merchantDeal","merchantNetwork"],
  ["checkout","interestFree","conversion"],
  ["conversion","merchantNetwork","gmv"],
  ["manager","onboarding","hr"],
  ["hr","email","recruiter"],
  ["recruiter","intern","candidate"],
  ["candidate","manager","offer"],
  ["burnout","offer","resignation"],
  ["achiever","kpi","bonus"],
  ["performanceReview","kpi","raise"],
  ["data","checkout","fraud"],
  ["fraud","code","riskEngine"],
  ["riskEngine","shopper","underwriting"],
  ["underwriting","shopper","creditLimit"],
  ["split4","checkout","downPayment"],
  ["payLater","split4","instalment"],
  ["instalment","interestFree","noLateFees"],
  ["tabbyCare","checkout","refund"],
  ["tabbyCare","bug","chargeback"],
  ["chargeback","shopper","dispute"],
  ["tabbyCard","tabbyApp","wallet"],
  ["wallet","shopper","topUp"],
  ["wallet","merchant","payout"],
  ["payout","code","ledger"],
  ["tabbyPlus","checkout","rewards"],
  ["rewards","shopper","loyalty"],
  ["riskEngine","manager","compliance"],
  ["compliance","retro","audit"],
  ["compliance","code","security"],
  ["compliance","launch","licence"],
  ["deadline","coffee","allNighter"],
  ["office","friday","freeLunch"],
  ["sprint","bug","blocker"],
  ["blocker","manager","escalation"],
  ["okr","kpi","northStar"],

  // ---- Finale ----
  ["launch","superApp","productOfYear"],
];
